import type { Metadata } from "next"
import "@/styles/tailwind.css"
import HeaderDesktop from "@/app/_components/HeaderDesktop"
import HeaderMobile from "@/app/_components/HeaderMobile"
import Hero from "@/app/_components/Hero"
import Footer from "@/app/_components/Footer"

export const metadata: Metadata = {
	title: "Legion Mariens Österreich",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body>
				<article className="mt-8">
					<HeaderMobile />
					<HeaderDesktop />
					<div className="max-container">
						<Hero />
						{children}
					</div>
					<Footer />
				</article>
			</body>
		</html>
	)
}

